### ISSUE TITLE
YahooJSON Disabled for EU IP Addresses

### ISSUE THREAD

**Issue by carlosala** [finance-quote/finance-quote#373] opened 2024-04-14 08:52 UTC
Hey! I was trying out the new way of fetching the crumb for yahoo_json and it doesn't seem to work.
The `gnucash-cli` reports that the URL that's being used is `https://query2.finance.yahoo.com/v11/finance/quoteSummary/?symbols=DOT-EUR&crumb={"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Cookie"}}}&modules=price,summaryDetail,defaultKeyStatistics`.
It seems like the cookie getting is not fully functioning.
Thanks!

**Comment by bpschuck** [comment] 2024-04-14 15:13
Closing - not released yet.

**Comment by carlosala** [comment] 2024-04-15 10:36
Isn't the `master` branch expected to be working?
It's ok if it doesn't, I didn't get it!
Thanks for the quick answer!

**Comment by andershm** [comment] 2024-04-16 14:10
I'm seeing this with the released version as well.

**Comment by carlosala** [comment] 2024-04-16 14:22
Yep, same here. @bpschuck shall we reopen? Are you able to fetch quotes?

**Comment by crowedavid** [comment] 2024-04-16 16:38
v1.60 update works for yahoo_json here as well:

```
[~] /Applications/Gnucash.app/Contents/MacOS/gnucash-cli --quotes info
Application Path /Applications/Gnucash.app/Contents/MacOS/gnucash-cli
Found Finance::Quote version 1.60.
[snip]

[~] /Applications/Gnucash.app/Contents/MacOS/gnucash-cli --quotes dump yahoo_json AAPL
Application Path /Applications/Gnucash.app/Contents/MacOS/gnucash-cli
Finance::Quote fields GnuCash uses:
    symbol: AAPL            <=== required
      date: 04/16/2024      <=== recommended
  currency: USD             <=== required
      last: 169.395         <=\
       nav:                 <=== one of these
     price:                 <=/
```

**Comment by carlosala** [comment] 2024-04-16 17:47
```
~ [ gnucash-cli --quotes info                                                               ]
Found Finance::Quote version 1.60.
[snip]
      
~ [ gnucash-cli --quotes dump yahoo_json AAPL                                               ]
Finance::Quote reported a failure for symbol AAPL: Error retrieving quote for AAPL. Attempt to fetch the URL https://query2.finance.yahoo.com/v11/finance/quoteSummary/?symbols=AAPL&crumb={"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Cookie"}}}&modules=price,summaryDetail,defaultKeyStatistics resulted in HTTP response 401 (Unauthorized)
~ [ gnucash --version                                                                       ]
GnuCash 5.6
Build ID: 5.6+(2024-03-30)
```

**Comment by bpschuck** [comment] 2024-04-16 19:42
To test purely F::Q without GnuCash calling it, on a Linux or Mac:

    # lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 22.04.4 LTS
    Release:	22.04
    Codename:	jammy
    
    # If you have installed 1.60 more than once (perhaps different
    # library paths), 1.60-0 may be 1.60-1 or 1.60-2, or ...
    cd $HOME/.cpan/build/Finance-Quote-1.60-0
    export PERL5LIB=$HOME/.cpan/build/Finance-Quote-1.60-0/lib:$PERL5LIB
    ./Examples/stockdump.pl yahoo_json AAPL
    $VAR1 = {
              'AAPLlow' => '168.27',
              'AAPLopen' => '171.71',
              'AAPLsymbol' => 'AAPL',
              'AAPLeps' => '6.42',
              'AAPLvolume' => 58572152,
              'AAPLisodate' => '2024-04-16',
              'AAPLname' => 'AAPL (Apple Inc.)',
              'AAPLdiv_yield' => '0.5501187',
              'AAPLcurrency' => 'USD',
              'AAPLdate' => '04/16/2024',
              'AAPLhigh' => '173.755',
              'AAPLtype' => 'EQUITY',
              'AAPLpe' => '26.457943',
              'AAPLlast' => '169.86',
              'AAPLyear_range' => '       162.8 - 199.62',
              'AAPLexchange' => 'NasdaqGS',
              'AAPLsuccess' => 1,
              'AAPLclose' => '172.69',
              'AAPLmethod' => 'yahoo_json'
            };
  
  If this works, but the GnuCash cli does not, the issue is not with F::Q.
  
    # This VirtualBox VM has GnuCash 4.8
    # Build ID: 4.8a+(2021-09-28)
    bschuck@vbox-ubuntu22:~$ gnc-fq-dump yahoo_json IBM
    Finance::Quote fields Gnucash uses:
           symbol: IBM                  <=== required
           date: 04/16/2024           <=== recommended
           currency: USD                  <=== required
           last: 183.88               <=\
           nav:                      <=== one of these
          price:                      <=/
          timezone:                      <=== optional
    bschuck@vbox-ubuntu22:~$

**Comment by carlosala** [comment] 2024-04-16 21:49
![image](https://github.com/finance-quote/finance-quote/assets/66907184/9ef25da1-ad17-431e-8bc7-2393c6bb0d0b)
Still not working for me 😢

**Comment by bpschuck** [comment] 2024-04-16 21:57
Remove F::Q and reinstall. It looks like your installation is corrupted somehow. Did you install via CPAN? Without being able to reproduce the issue, there is nothing to fix.

**Comment by bpschuck** [comment] 2024-04-16 22:09
You can also try `DEBUG=1 ./stockdump/.pl yahoo_json AAPL`. But I'm curious, why is your version of `stockdump.pl` in `~/D/d/f/Examples` and not `$HOME/.cpan/build/Finance-Quote-1.60-01/`?  Was this module installed using CPAN (cpan)or CPANMinus (cpanm)?

**Comment by carlosala** [comment] 2024-04-16 22:14
I just cloned the repo.
![image](https://github.com/finance-quote/finance-quote/assets/66907184/54dfc84b-2d7d-48d8-954f-0cc2f507cdf1)

**Comment by bpschuck** [comment] 2024-04-16 23:17
Please install Finance::Quote properly using `cpan` or `cpanm`. I explained testing exactly from where CPAN leaves module source for a reason...

 Please use cut and paste to send output instead of screen shots. Test using `stockdump.pl` **EXACTLY** as I posted. Include other info such as OS version, GnuCash version, etc.

**Comment by carlosala** [comment] 2024-04-17 07:01
I'm using Arch Linux, but I can reproduce as well in a ubuntu-22.04 docker image.

```
# installed using `cpan Finance::Quote`
$ cd .local/share/.cpan/build/Finance-Quote-1.60-2
$ export PERL5LIB=$PWD/lib:$PERL5LIB
$ DEBUG=1 ./Examples/stockdump.pl yahoo_json AAPL
### [Wed Apr 17 08:59:30 2024]    cookie_jar : bless( {
###                                                     COOKIES => {
###                                                                  'login.yahoo.com' => {
###                                                                                         '/' => {
###                                                                                                  AS => [
###                                                                                                          0,
###                                                                                                          'v=1&s=pdMraThU&d=A6620c4d1|itU7Kpb.2SoujXrNK8pQPMiR2FSF2cQgqnsxU3jIrnirgEXjuRm71D2y8jcgcLPk2C5JuF505Ysv8GYbyctj9ZuKK5XNqoP5rV4EGTy6z1YosofUiLLKKlURsD91P7Ui7ULBQQHPTOnX__9Ot9GUQDEpH9Mx3Fd7teY1YfvcsCofGd_dZW4m2w24JdsNi5c78pl443Iwdj1VnkgHKR_yoPEuwHQwJxP75PHmgz5aHCR3x066S60d1UxuVlW5vu_sjmn2USEnhEKGcmv1DLVF3BpkeLvQYP2eE7fJEUmeenTqhKHESLr1aH8UtReQqXD65OcqbIvRmaU9zZYWhIu5oSgG9oBL68nSTuP4InU1OiYBhR3_21mg6r8cBGob2Fdy4LVP68OI84FM7s98R.kTIvc3HSnz9alFz6HWWkspE_Lsb2WFU1svNvubNQiE_nHRCcD2K6fEQ0oi2ucpdZFFSKwz_EAcKoH1gsRTo4xekLmrNSW0Bcf.pvQB9QwuXNj8r709grYQdx94QX9qAfeOf8HReNmVzUlzFkKfe1cO5TTHquTcJscXXRSqUJtlpi.ygN0U5eReJTe4po.cm7.yMRCsf0ifEhuzNHJkQVfOsW4h11rgkgXDKLhNtWIXT2yqEd9GizHZCpQC9S6coxGIPL0IDExcjQWT7vpsmXEnmlHw3pkUdWxGCMXworgyH0bA2ejXPKkyF_sEZlExosfDP8YVbaY-~A',
###                                                                                                          undef,
###                                                                                                          1,
###                                                                                                          1,
###                                                                                                          undef,
###                                                                                                          1,
###                                                                                                          {
###                                                                                                            HttpOnly => undef
###                                                                                                          }
###                                                                                                        ]
###                                                                                                }
###                                                                                       }
###                                                                }
###                                                   }, 'HTTP::Cookies' )
### [Wed Apr 17 08:59:30 2024]         crumb : '{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Cookie"}}}'
$VAR1 = {
          'AAPLsymbol' => 'AAPL',
          'AAPLerrormsg' => 'Error retrieving quote for AAPL. Attempt to fetch the URL https://query2.finance.yahoo.com/v11/finance/quoteSummary/?symbols=AAPL&crumb={"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Cookie"}}}&modules=price,summaryDetail,defaultKeyStatistics resulted in HTTP response 401 (Unauthorized)',
          'AAPLsuccess' => 0
        };
```

**Comment by bpschuck** [comment] 2024-04-17 19:10
It could be another Perl module or package not working quite right. You should have more cookies in the response.

Try this. In `YahooJSON.pm`, immediately after the line `$reply = $ua->request(GET 'https://login.yahoo.com');` add the line `### [<now>] Headers from Login: $reply->headers_as_string` so it looks something like:

    # get Yahoo cookies that are needed for crumb
    $reply = $ua->request(GET 'https://login.yahoo.com');
    
    ### [<now>] Headers from Login: $reply->headers_as_string
    
Then execute `stockdump.pl` again with `DEBUG=1` being set. There should be 4 `Set-Cookie:` lines in the returned header. If not, there is another module somewhere in the dependency chain that needs to be updated or reinstalled.

Aside from other header data, I get:

    Set-Cookie: AS=v=1&s=MGH4tJ6c&d=A66216ca3|jsIyFfr.2SpjePepLbJojpp0iCf80vai4E7LyWHYg1PvRVumNyQ4jt4oKW56Ykx.5ySN5v4ku3v5URjQrQqIzRS4n0hWr7Q5j1P3Sh592KVjtGpsnngD.KL89X5VPGbgrqLB_ISXHZZOSWkmIYtm.VaEloqwkucGnok.L.QoJkTscLVXPfZ6LAZrXIloHMSCZ.VgV8j44BeRG825NV4RzzvBaeBkq3NdVapnMUYKp1fVAWS3rUoTL8ITxkMFFx0X4LDauyUE7nWEBhVQs2J1nS8g.7a0NshG0UD8wu_tROBsjXL05fuMNw_S6FjNNYFyyou1.RgkCe7nr_FqU6Sfbs5KFfJNt71b8yfrDA0_YaY6bSOOgkSd5AnY1JLALJj7b.CKFbz9xEnhwIenD1E3woxx9ku4q9OqdsQV4O5YSChemm6JGMDBxQAeTWIwWxzQLpMVaa_ZdxKs51Hryqpe0MSIL5La7qpZe3ZsDtq4ROd0dA6MLbHIyUC9pBps9j0tfZHqSB3MV9RKjgVMN.04sDrXPGkvB6M6dNtzsXejNRyqYrJtu2r0WNKNCu9ia1Fqn643ZiKgCvtylPDyshJ54iQoVVzDFb2C3OcLjIQ4J36JcU8mKjA.dWBcpKuaGiw8arYi5voap12YAuZEa.aaDT_KSCs2gKJud8VCbg0AFnGLct7yMwYglAFA7scZpNnP2MUq5Ryuk_pYSESeOthrfEwyp0_RYB.Gb2r0kl9O.kHashVCiWwW5EQ6eKMZGs5zw88PGPMPYm8.nySj1kWeQ05oemp9~A; path=/; domain=login.yahoo.com; secure; HttpOnly
    Set-Cookie: A1=d=AQABBCMbIGYCEGFjuJgHLR2c_L2I8nqRFrUFEgEBAQFsIWYpZtwr0iMA_eMAAA&S=AQAAAvw0xqWRpP-b3nccQVMNXMA; Expires=Fri, 18 Apr 2025 00:55:31 GMT; Max-Age=31557600; Domain=.yahoo.com; Path=/; SameSite=Lax; Secure; HttpOnly
    Set-Cookie: A3=d=AQABBCMbIGYCEGFjuJgHLR2c_L2I8nqRFrUFEgEBAQFsIWYpZtwr0iMA_eMAAA&S=AQAAAvw0xqWRpP-b3nccQVMNXMA; Expires=Fri, 18 Apr 2025 00:55:31 GMT; Max-Age=31557600; Domain=.yahoo.com; Path=/; SameSite=None; Secure; HttpOnly
    Set-Cookie: A1S=d=AQABBCMbIGYCEGFjuJgHLR2c_L2I8nqRFrUFEgEBAQFsIWYpZtwr0iMA_eMAAA&S=AQAAAvw0xqWRpP-b3nccQVMNXMA; Domain=.yahoo.com; Path=/; SameSite=Lax; Secure

**Comment by bpschuck** [comment] 2024-04-17 19:46
Only one cookie. From a module that while F::Q needs it, is not an F::Q issue. 

Try this, somewhere near the top of YahooJSON.pm (maybe around line 34) add the lines:

    use LWP::Protocol::http;
    push(@LWP::Protocol::http::EXTRA_SOCK_OPTS, MaxLineLength => 0);
    
This is just a stab in the dark though.

**Comment by bpschuck** [comment] 2024-04-17 19:51
And another using curl

`curl --include https://login.yahoo.com` or `curl --head https://login.yahoo.com`

What cookies are being returned?

**Comment by carlosala** [comment] 2024-04-17 19:59
Same, only 1 cookie.

**Comment by bpschuck** [comment] 2024-04-17 20:01
> Same, only 1 cookie.

Using curl?

**Comment by carlosala** [comment] 2024-04-17 20:01
> Using curl?

Yas. I tried with several IPs and still.

**Comment by bpschuck** [comment] 2024-04-17 20:32
Unfortunately what I expected. Curl isn't based on Perl. Which means there is something about your system/environment that is the underlying root cause. Simply put, this isn't a Perl/F::Q issue. **But** it does affect F::Q users. 
For me it's been working fine on Ubuntu 22 here at the office, Ubuntu 22 on my home desktop, Mac OSX Catalina (10.15) home and office, and Windows 10 home and office. While I live and and work in California, the `curl` command returns 4 cookies when executed on a NetBSD 10 system in New York city.

**Comment by carlosala** [comment] 2024-04-17 22:19
I tried as well from a Raspberry PI running debian and I have the same result (different country, I tried from Sweden and Spain).
I'll keep trying to see if I find anything.

**Comment by bpschuck** [comment] 2024-04-18 00:31
Please see what cookies you get with `curl --location --include --cookie-jar /tmp/cookies 'https://login.yahoo.com/config/login'.

If there are 4, change the line in YahooJSON.pm to that instead of just `https://login.yahoo.com`.

**Comment by carlosala** [comment] 2024-04-18 07:33
Still just one cookie. Trying with a VPN, I see that when I use a US VPN it answers the four cookies, and with any European IP I tried only one cookie.

**Comment by bpschuck** [comment] 2024-04-18 14:10
Thanks.

One last shot in the dark. Please try this curl command:

`curl -location --include --cookie-jar /tmp/cookies https://login.yahoo.com/?.lang=en-US&src=finance&.done=https%3A%2F%2Ffinance.yahoo.com%2F&pspid=1183300002&activity=ybar-signin`

or 

`curl -location --include --cookie-jar /tmp/cookies https://login.yahoo.com/?.lang=en-US&src=finance&.done=https://finance.yahoo.com/&pspid=1183300002&activity=ybar-signin`

**Comment by carlosala** [comment] 2024-04-18 14:46
Same as before, just 1 cookie. Outside of the EU (this time I tried Albanian IP) I get 4 cookies.

**Comment by bpschuck** [comment] 2024-04-18 15:13
Thanks again for that information. At the very least you have a work-around using a VPN. I am assuming F::Q works while you are using the VPN that gives you a US IP? Another gentleman, @ka-patel and myself are looking for other ways to get the proper cookies set, he more than I.

**Comment by crowedavid** [comment] 2024-04-18 16:30
this would appear to be for yahoo GDPR compliance.

https://developer.yahooinc.com/datax/guide/gdpr/cookiemapping/

**Comment by bpschuck** [comment] 2024-04-18 16:35
Note to self: Need to review https://developer.yahooinc.com/datax/guide/gdpr/cookiemapping/

**Comment by carlosala** [comment] 2024-04-18 16:41
Thank you so much! Sorry for the noise🥲🥲

**Comment by ka-patel** [comment] 2024-04-18 19:10
From the help of VPN, I have reproduced the issue. I have also built updated flow (with the help of a person who was having the issue in Germany) that works from multiple locations: Frankfurt (Germany), Mumbai (India), Johannesburg (South Africa), Australia, the US and UAE. I believe that should cover good deal of users base from different geos.

In the YahooJSON.pm module of version 1.60, replace lines 82 through 83:

> _-- original code lines --_
```
    # get Yahoo cookies that are needed for crumb
    $reply = $ua->request(GET 'https://login.yahoo.com');
```

with following lines:

> _-- replacement code lines --_
```
    # get initial Yahoo cookie -- A3 
    $reply = $ua->request(GET 'https://fc.yahoo.com');

    # get rest of Yahoo cookies -- A1 and A1S 
    $reply = $ua->request(GET 'https://www.yahoo.com');
```
And then give a try of getting quotes.

**Comment by carlosala** [comment] 2024-04-18 19:14
Works for me! @ka-patel

**Comment by bpschuck** [comment] 2024-04-18 19:19
Thank you Kalpesh. 

From an IP that has the issue, could you try replacing the single `https://login.yahoo.com/` with `curl -location --include --cookie-jar /tmp/cookies https://login.yahoo.com/?.lang=en-US&src=finance&.done=https://finance.yahoo.com/&pspid=1183300002&activity=ybar-signin&gdpr=0' in the original  code? More for my personal curiosity. 

Otherwise the two line solution you discovered will have to do for now. 

Thanks.

**Comment by ka-patel** [comment] 2024-04-18 19:29
@bpschuck - From the states it works but from Frankfurt it fails:

```
### AlphaVantage->new args : {}

### [Thu Apr 18 15:27:52 2024]    cookie_jar : bless( {
###                                                     COOKIES => {
###                                                                  'login.yahoo.com' => {
###                                                                                         '/' => {
###                                                                                                  AS => [
###                                                                                                          0,
###                                                                                                          'v=1&s=a7XxlcYJ&d=A6622c5b7|jB_59qf.2Sou2e65fMjl.eMo0fh0GOBVazWdYoAU6B8MeTPJNPK_jDNKj4cX_3_u.esGarzjtnz7.rtTo3LU_sUXpCGEwFD2HieJY82WvrZW8hkkGYWcYPS.igin6GTKYole0J4ugtJgE3gzxYDCZ18Ytp7HkvdHFkfuTAXlc53nEtWitRCxHtMt0YWzOEz0nn2surFC2Doe9wrjXBC1WN82WwJsCoonrxA3ccxFn1d0joKrLJIaYIU.sAl.cSFAueNVXtfug5kaIjriVGMmbz7KQKRtSS_ZgIxn6YGf2JvqHBGxuPKHFWRZ9ErnX4wAFxDo3QPYPvtRrLQMRXOuQ5JX6RDGNMWOT5moprB5fxgGHPyud3sfEtk97KYwNuk3EZhz9DPM4xrcIuzajnEJ5rbp76vfYmko.4weShND0E4c_32nw803GE4ZB6qlvuEBkG7qFZQ6i8VTCwhb_zfQyve3HITtA9l1ILIcKlpU_FdctIbVvsWWyAdK97tXox31ESl4CKx7uz_h.T93nW_Edk99DQSh1v93BisCG7HasDPNMkJu7i9RdcUuErquSsbT3glOr2L6P40PJA0aQrGz9J5LUfRuqNVRdCYrSicK8vszw.azxRfqJwKnSwVe7GG1yDVbkrmSs6zUuEjGdlMy52yMg0lDODGxuqPSNbDOqseFNv9IHGuMMV_w7FxlA4DFVT5vzfXep4VtJvmzC5Rm6K073gQ5lCzK3O7X5uEdNvxYenpisdjcJqo6I72oEQ--~A',
###                                                                                                          undef,
###                                                                                                          1,
###                                                                                                          1,
###                                                                                                          undef,
###                                                                                                          1,
###                                                                                                          {
###                                                                                                            HttpOnly => undef
###                                                                                                          }
###                                                                                                        ]
###                                                                                                }
###                                                                                       }
###                                                                }
###                                                   }, 'HTTP::Cookies' )
### [Thu Apr 18 15:27:52 2024]         crumb : '{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Cookie"}}}'

```

**Comment by ka-patel** [comment] 2024-04-18 19:46
Curl version:

```
kapatel@kalpesh-desktop:~$ curl -location --include --cookie-jar /tmp/cookies 'https://login.yahoo.com/?.lang=en-US&src=finance&.done=https://finance.yahoo.com/&pspid=1183300002&activity=ybar-signin&gdpr=0'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38443  100 38443    0     0  65047      0 --:--:-- --:--:-- --:--:-- 64937
kapatel@kalpesh-desktop:~$ cat /tmp/cookies
# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.login.yahoo.com      TRUE    /       TRUE    0       AS      v=1&s=buPrFaxT&d=A6622c9e3|EaB7O.v.2SryOlE0TFepiX84kML2f5NBrqUZmFEZO.Xv_szbU165ZyNiVcCBy4_TwJJ.RHoBkcPpJRB5JMZ02KthlxuVu.AlpJbdZD1kHddWZu2tMzQ03.Gj0pKDxDThvqTdARHrquqntYb0aEofyVAaPJdCaCDIfpwzwgiqEguJcg7gGwu1XXVm96gEHjFjpgDbl0Eam7CyhePbTNiu4uAY8uo9y3tyh55OSI4mdoVZbkOeCCCDN5Klhm7zhdpgHI0bznrss5THeTvNVWie22msnLZtfQXL2C2m2zwynJ5n87Qw7PfkMKTjthj9OzRTlDjRaPiDGSlXSWGAs6YJNxdbF_mkw7eqWJncdzhlLjt_bvdk_pxi.W5bvaLcxPZRyFvgOTpMwDHQry9H.f0a85CKbKR0LTcbfVuxNCe21NSepROJkIMcBVqAy3HqhhHbW7DPEG_xfMuElb8Iu3Y4r.33rG2ikQy04ZGN1fcLWR6wGSVVIK15elq3O3v8.jX0noUcFvwI9zNTs77DcRWXBqRxIcRn4EoET2wNLOPMT6RC0dGUQIkod7xJ26N6kw_EEIGmDN.42RhleS4_ZOw9z9S1XGj3etdaOeFeVTsPeeejfP_CjKi88w7uSU_.9H6Tw5.L95C6OhAlnzTPMeL2rDQq_zrusfqCqNq_I3t5Ch3H3COvjjjHahW3uaInnoRtgP15KM5o8VBIKMWLD5pOsa8xPQbV45F0PQaa56U162nMq7IQUcwHlNHWMXE-~A
kapatel@kalpesh-desktop:~$
```

**Comment by bpschuck** [comment] 2024-04-18 20:43
Thanks @ka-patel for your looking into this. I'll get everything squared away later today.
Thanks again @carlosala for doing a bunch of testing for us.

**Comment by bpschuck** [comment] 2024-04-19 01:33
Pre-release v1.60_01 pushed to CPAN.
BPSCHUCK/Finance-Quote-1.60_01.tar.gz

**Closed** 2024-04-19 02:04 UTC
Labels: non-issue

**Comment by ka-patel** [comment] 2024-04-19 11:24
@bpschuck - Looking for thoughs here: while this "hack" works fine for everywhere, I want to put a bit more logic to hit login first and then hit others if cookies are missing. fc could go away without notice but login is unlikely.

**Comment by bpschuck** [comment] 2024-04-19 16:17
I hate to say it, but there is a point at which you cannot please everybody. Note the recent post on the GnuCash-User list from Klaus Dahlke in Germany. 

The underlying issue will continue as web sites that allow people to look up stock prices work on making it difficult or impossible to gather that data automatically. Companies like AlphaVantage, MarketWatch, Fool, and others pay big $$ for data feeds. Part of those contracts likely stipulate that they do make that easily available for others to gather programmatically. My first job in IT was a small software/consulting shop that dealt with market data in 1986 -> 1992. Hell, we paid a lot of money for a nightly tape that was picked up by a courier and then loaded onto our mainframe for processing. When we finally installed a satellite feed (I *think* the company name was "ComStock") with live data, that was big bucks.

**Comment by ka-patel** [comment] 2024-04-20 13:30
Indeed, market data is expensive. I recall when negotiating with Reuters back in early 2000 that it was not cheap and they definitely wanted to limit as to who received those feeds, at least for real time ones. Anyways it was a thought to bit bullet proof it for the future or at least minimize the issues to the user community and in the process try to reduce its exposure. Not that it will matter with Yahoo as they will yank it if they are bent on doing so. It is trivial enough of a to be done later.
