### ISSUE TITLE
ASX source stopped working?

### ISSUE THREAD

**Issue by slowbart** [finance-quote/finance-quote#166] opened 2020-10-13 06:12 UTC
Some time around 11 Oct 2020 my Gnucash install stopped receiving stock quotes from ASX. No changes made to either Gnucash of F::q

Quotes still work from e.g. yahoo_json for the same stock codes. Output below from ASX (failed with **errormsg: Failed to parse HTML table.**) and then Yahoo (working).

Can anyone help please?
```
$ /Applications/Gnucash.app/Contents/Resources/bin/gnc-fq-dump -v asx AFI
Finance::Quote fields Gnucash uses:
    symbol: AFI (deduced)        <=== required
      date: ** missing **        <=== recommended
  currency: ** missing **        <=== required
      last: **missing**          <=\       
       nav: **missing**          <=== one of these
     price: **missing**          <=/        
  timezone:                      <=== optional

** This stock quote cannot be used by GnuCash!


All fields returned by Finance::Quote for stock AFI

stock           field  value
-----           -----  -----
AFI          errormsg: Failed to parse HTML table.
AFI              last: **missing**
AFI               nav: **missing**
AFI             price: **missing**
AFI           success: 0

$ 

$gnc-fq-dump -v yahoo_json AFI.ax
Finance::Quote fields Gnucash uses:
    symbol: AFI.ax               <=== required
      date: 10/13/2020           <=== recommended
  currency: AUD                  <=== required
      last: 6.57                 <=\       
       nav:                      <=== one of these
     price:                      <=/        
  timezone:                      <=== optional

All fields returned by Finance::Quote for stock AFI.ax

stock           field  value
-----           -----  -----
AFI.ax          close: 6.45
AFI.ax       currency: AUD
AFI.ax           date: 10/13/2020
AFI.ax      div_yield: 3.7209302
AFI.ax            eps: 0.199
AFI.ax       exchange: Sourced from Yahoo Finance (as JSON)
AFI.ax           high: 6.57
AFI.ax        isodate: 2020-10-13
AFI.ax           last: 6.57
AFI.ax            low: 6.47
AFI.ax         method: yahoo_json
AFI.ax           name: AFI.ax (AUS.FOUND. FPO)
AFI.ax           open: 6.47
AFI.ax             pe: 33.015076
AFI.ax        success: 1
AFI.ax         symbol: AFI.ax
AFI.ax           type: EQUITY
AFI.ax         volume: 454372
AFI.ax     year_range:         4.77 - 7.32

$
```

**Comment by slowbart** [comment] 2020-10-13 09:47
Oh, I see the problem. Looks like ASX ha upgraded their website over the weekend. The server is responding with:

HTTP/1.0 302 Moved Temporarily\r\n

**Comment by CleanShed** [comment] 2020-10-14 05:37
I've examined the Perl Finance::Quote ASX.pm module used by GnuCash to fetch price data from the Australian Securities Exchange (ASX) and can confirm that this problem is caused by an upgrade to the ASX web site:

"Please note that the ASX beta site is a test website and is still undergoing final testing before its official release. The sole purpose of this beta site is to conduct testing and obtain feedback on the quality, usability, performance and the identification of defects. The beta site and all content found on it should not be relied on. Please refer to asx.com.au for the most up to date content and information."

When I reviewed the new web site I discovered a JSON API that provides the necessary information, and I have adapted the perl ASX.pm module to use this API instead.  I have only tested the changes on Windows 10 with GnuCash 4.1.

If anyone is interested, I have attached a copy of the modified perl module to this comment

I am totally unfamiliar with the process to get changes made to Finance::Quote and do not know what (if anything) to do next?

To use this module, all you need to do is:
(1) Locate the Finance::Quote directory in your Perl installation, eg
C:\Strawberry\perl\site\lib\Finance\Quote\

(2) Rename the existing ASX.pm file to something like ASX.pm.ORIGINAL

(3) Put the attached ASX.pm.txt file in the same directory

(4) Rename it to ASX.pm

(5) Test it with the GnuCash gnc-fq-dump utility:
`C:\Program Files (x86)\gnucash\bin>perl gnc-fq-dump ASX BHP`
`Finance::Quote fields Gnucash uses:`
`    symbol: BHP                  <=== required`
`      date: 10/14/2020           <=== recommended`
`  currency: AUD                  <=== required`
`      last: 36.1                 <=\`
`       nav:                      <=== one of these`
`     price: 36.1                 <=/`
`  timezone:                      <=== optional`

[ASX.pm.diff.txt](https://github.com/finance-quote/finance-quote/files/5375829/ASX.pm.diff.txt)

[ASX .pm.txt](https://github.com/finance-quote/finance-quote/files/5375825/ASX.pm.txt)



Hope this helps.

**Comment by wrd2093** [comment] 2020-10-14 07:15
> Hope this helps.

It did! Thanks for taking the time to post your change.

**Comment by fellen** [comment] 2020-10-14 11:32
@CleanShed can you read the github guide '(link on top) and convert your attachment in a Pull Request?

**Comment by CleanShed** [comment] 2020-10-14 11:36
> @CleanShed can you read the github guide '(link on top) and convert your attachment in a Pull Request?

I'll have a crack tomorrow Frank - new to git.

**Comment by vincentl** [comment] 2020-10-14 13:03
Section 4 of https://github.com/finance-quote/finance-quote/blob/master/Documentation/Hackers-Guide also has some instructions for how to create a pull request.  If you run into any trouble, just comment back here.  By doing a pull request, the git history will show your contribution!

**Comment by CleanShed** [comment] 2020-10-15 04:33
Thanks for the encouragement @vincentl , there is a bit more to this than I thought and I'd like to take the time to do it right, so it will probably take me a few days get up to speed.  I'll certainly come back here if I get stuck!

**Comment by CleanShed** [comment] 2020-10-17 03:38
Hi @vincentl I am working my way through the Hackers Guide you cited above and have encountered an issue at the end of Step C.  I successfully installed all of the "listdeps" modules and the "authordeps" modules, but three of the latter still show up as missing despite installing them several times.  The three in question are:
`E:\Git\finance-quote>dzil authordeps --missing`
`Dist::Zilla::Plugin::Git::NextVersion`
`Dist::Zilla::Plugin::PodSyntaxTests`
`Dist::Zilla::Plugin::Twitter`

and here is the tail end of the "successful" installation of one of them:
`Files=25, Tests=202, 89 wallclock secs ( 0.20 usr +  0.09 sys =  0.30 CPU)`
`Result: PASS`
`  ETHER/Dist-Zilla-Plugin-Git-2.047.tar.gz`
`  C:\Utility\STRAWB~1\c\bin\gmake.exe test -- OK`
``
`cpan> install Dist::Zilla::Plugin::Git::NextVersion`
`Dist::Zilla::Plugin::Git::NextVersion is up to date (2.047).`
``
`cpan> exit`
`Lockfile removed.`
``
`E:\Git\finance-quote>dzil authordeps --missing`
`Dist::Zilla::Plugin::Git::NextVersion`
`Dist::Zilla::Plugin::PodSyntaxTests`
`Dist::Zilla::Plugin::Twitter`
``
`E:\Git\finance-quote>`

Does this actually matter?  I did a test run successfully:
`E:\Git\finance-quote>dzil test`
`[DZ] building distribution under .build/LleVTTgZMG for installation`
`[DZ] beginning to build Finance-Quote`
`[Git::NextVersion] Bumping version from 1.49 to 1.50`
`[DZ] guessing dist's main_module is lib/Finance/Quote.pm`
`[@Basic/ExtraTests] rewriting author test xt/author/pod-syntax.t`
`[DZ] writing Finance-Quote in .build/LleVTTgZMG`
`[MarkdownInRoot] overriding README.md in root`
`Checking if your kit is complete...`
`Looks good`
`~~ snip ~~~`
`t/za.t ................. skipped: Set $ENV{ONLINE_TEST} to run this test`
`t/za_unittrusts.t ...... skipped: Set $ENV{ONLINE_TEST} to run this test`
`All tests successful.`
`Files=73, Tests=151, 32 wallclock secs ( 0.25 usr +  0.20 sys =  0.45 CPU)`
`Result: PASS`
`[DZ] all's well; removing .build/LleVTTgZMG`
`>`

Thanks

**Comment by CleanShed** [comment] 2020-10-17 09:33
Also I ran the TEST_AUTHOR and ONLINE_TEST test sets and it was not a pretty sight:
`t/za.t               (Wstat: 2560 Tests: 17 Failed: 10)`
`  Failed tests:  3-8, 11-14`
`  Non-zero exit status: 10`
`t/za_unittrusts.t    (Wstat: 1536 Tests: 10 Failed: 6)`
`  Failed tests:  2-4, 6-8`
`  Non-zero exit status: 6`
`Files=73, Tests=1890, 676 wallclock secs ( 0.38 usr +  0.19 sys =  0.56 CPU)`
`Result: FAIL`
`Failed 31/73 test programs. 366/1890 subtests failed.`
`gmake: *** [Makefile:1004: test_dynamic] Error 6`
`error running gmake test`
``
`E:\Git\finance-quote>`

Is this expected behaviour?  I need to establish a baseline before I can make any changes.

Thanks again

**Comment by Trentan** [comment] 2020-10-18 03:32
> Hope this helps.

Surely did, thanks for this working again (asx site change).

**Comment by CleanShed** [comment] 2020-10-18 03:54
> From what I can see in the changes you made, the previous iteration was doing a batch type retrieval of multiple codes (to a max count of 10 per fetch/get) and this script change now does individual fetches for each code (not as efficient, but does the job nonetheless) - unless there is a api call on asx.com.au that can return multiple codes prices, might be the best alternative.

That's correct @Trentan   - any suggestions for a (free) alternative data source are most welcome.  There is no shortage of paid APIs: [https://www.asxonline.com/mia/](https://www.asxonline.com/mia/)

**Comment by vincentl** [comment] 2020-10-21 12:05
@CleanShed - sorry it has taken me a bit of time to reply.

* I'm not sure why dzil authordeps --missing is still reporting packages missing
* We are trying to work our way through all the failed tests before the 1.50 release, but yes, it isn't pretty right now!
* The most important thing is that the following runs with no errors
   TEST_AUTHOR=1 ONLINE_TEST=1 dzil run prove -lv t/asx.t

As a side note, I just added a section to the Hackers-Guide on a new strategy for embedding development and debugging code in modules.  If you have some debugging code in ASX.pm, I would appreciate some feedback on the new strategy.

**Comment by CleanShed** [comment] 2020-10-22 11:10
Hey @vincentl , no need to apologise, we all have busy lives ;--)

1.  Good news - when I run "TEST_AUTHOR=1 ONLINE_TEST=1 dzil run prove -lv t/asx.t" it comes up clean:
`ok 35 - Last price for WES was > 0`
`ok`
`All tests successful.`
`Files=1, Tests=35, 13 wallclock secs ( 0.06 usr +  0.00 sys =  0.06 CPU)`
`Result: PASS`
`[DZ] all's well; removing .build/BAboyQ8rxF`

2.  This may all be academic as @jvolkening has come up with a parallel solution to this issue.  I've tested it and left some comments on his ASX #170 issue.  I'm a newbie and I am happy to let him run with it.

3.  You asked for some feedback on the strategy of using Smart::Comments and $ENV{DEBUG}
The internet is full of opinions, right, so here is one more - feel free to ignore.
Any aids to support / debugging are welcome.  I personally am inclined towards logging (Log:Log4perl) and have not used Smart::Comments but had a read up and I can see that it would be useful.  Standards are important, so if that is the standard for Finance::Quote then I am happy to use it and can add some suitable code to ASX.pm and t/asx.t.

4.  Some questions back to you.  Who is the audience for the DEBUG output?   Is it primarily the developers supporting and enhancing the code, or the end users who encounter problems running it?
Have you considered some name qualification on DEBUG?  If lots of modules are instrumented this way, turning it on could spew out a huge amount of irrelevant information.  How about using module names to narrow the scope, for example DEBUG-Finance-Quote?  Or is this too cumbersome?

**Comment by CleanShed** [comment] 2020-10-23 06:30
Update re:
> 2. This may all be academic as @jvolkening has come up with a parallel solution to this issue.  I've tested it and left some comments on his ASX #170 issue.  I'm a newbie and I am happy to let him run with it.

@vincentl : @jvolkening has passed this over to me to run with (see comments in #170)  I'll keep you updated here.

**Comment by vincentl** [comment] 2020-11-16 12:39
@CleanShed - checking in.  Do you plan to open a pull request or should we build off of @jvolkening PR #170?

**Comment by CleanShed** [comment] 2020-11-17 11:55
Hi Vincent

Sorry this has been taking so long, I have been on holidays.

I need to do more more testing.  When do you need it by?

Thanks

Geoff
=====

**Comment by vincentl** [comment] 2020-11-17 13:10
Hi Geoff - No problem.  I'm currently working my way through all the modules to validate the tests and remove dead modules.  I still have dozens to look at, so no rush.  Just wanted to check in and see that you were still interested in finishing the update.

**Comment by CleanShed** [comment] 2020-12-02 22:27
Hi Vincent

Just a quick update.  From a list of 2,003 ASX listed companies I was 
able to successfully retrieve price data for 1,994 (99.6%) so these new 
JSON data sources are looking good.

I am on holiday for a couple of weeks and will be off the air until 
Christmas.

Regards

Geoff
=====

**Comment by vincentl** [comment] 2021-01-03 21:46
@CleanShed  - Geoff - I hope you had a nice holiday! I have finally dealt with all the modules except ASX for the next FQ release.  So, I don't want to pressure you but would like to wrap up a new release soon.  Let me know your status.  Thanks!

**Comment by CleanShed** [comment] 2021-01-05 21:51
Hi Vincent

Happy New Year!

I'm back from holidays at the end of this week and will have a release 
for you next week.

Regards

Geoff
=====

**Comment by CleanShed** [comment] 2021-01-14 10:45
Hi Vincent

I have created a pull request for my changes to ASX.pm and asx.t, 
summary below.

https://github.com/finance-quote/finance-quote/pull/172

They have been tested on both Windows 10 and Linux.

Please let me know if you need anything else.

Regards

Geoff
=====

lib/Finance/Quote/ASX.pm
October 2020 the ASX revamped their website with dynamic content for 
quotes which prevented the previous HTML screen scraping from working, 
but exposed a number of JSON data sources, two of which are used here.
The primary source returns data elements for almost all securities, but
does not return prices for certain security types (some bonds and 
exchange traded products, options, and warrants), and returns an error 
for indices.  The alternate source returns less data elements, but 
provides usable quote data for all the known exceptions, including 
indices.  This version will always call the primary source, and call the 
alternate if a price is not returned by the primary.

Smart::Comments implemented to conform with the Hackers Guide:
https://github.com/finance-quote/finance-quote/blob/master/Documentation/Hackers-Guide

t/asx.t
Update the list of securities to test against.
Include additional types of securities:
Corporate Bonds
Government Bonds
Exchange Traded Products (eg ETFs)
Refactor into sub tests by security type.
Update the data elements to be tested.
Skip data element tests when security not found.

=====

**Comment by vincentl** [comment] 2021-01-15 02:02
Fixed in merge c03ac9c0e0d0615c4d72ee088c26e0e6f63832d5

**Closed by vincentl** 2021-01-15 02:02 UTC
Labels: next release

**Comment by dmoverton** [comment] 2021-05-20 04:36
@vincentl any idea when this will be released? I've been waiting since October for a fix for this bug to be released.

**Comment by bulletmark** [comment] 2021-05-20 04:38
@dmoverton I got tired of waiting so created [this alternative](https://github.com/bulletmark/gnucash-asx-fetch) months ago.

**Comment by Trentan** [comment] 2021-05-20 04:43
> @vincentl any idea when this will be released? I've been waiting since October for a fix for this bug to be released.

Why not just use latest file - asx.pm from commit
"Fixed in merge c03ac9c"?

https://github.com/finance-quote/finance-quote/commit/c03ac9c0e0d0615c4d72ee088c26e0e6f63832d5#diff-ce4cf0434d952cdf1b898bec7955d31e30592acfe6e47c88f815e13cc280f60e

**Comment by dmoverton** [comment] 2021-05-20 05:13
I could, but I'd rather not overwrite random source files. I've been thinking surely there will be a new official release soon, but maybe it's just time to bite the bullet...

**Comment by vincentl** [comment] 2021-05-20 11:54
@Trentan - I don't have control of the CPAN release process.  

There are a few open issues that should be easy to fix and a few pull requests that should be merged before a final release, but there isn't much of an active Finance::Quote development team, so everything moves **really** slowly.  Whenever I get time to address those or whenever someone else volunteers to join the development team and wraps up those final items, we can reach out to the previous developers that still have CPAN release rights to get 1.50 out.  If that fails, CPAN has a process for recovering abandoned projects that we would have to pursue.
