### ISSUE TITLE
quotes install fails: `t/exit_with_message.t ... Use of uninitialized value $err in pattern match`

### ISSUE THREAD

**Issue by diablodale** [finance-quote/finance-quote#325] opened 2023-07-28 12:57 UTC
Online quotes install bundled with gnucash 5.3 fails. Reports testing error, then warns and prompts...
`chances to succeed are limited`, and prompts `Use unaligned loads and stores? yes/no [no]`

note: cross-posting issue as gnucash bugzilla https://bugs.gnucash.org/show_bug.cgi?id=798994 is zombied.

### Setup

* Microsoft Windows [Version 10.0.22621.1928]
* turn on the Windows sandbox feature

### Repro

1. Install Windows
2. Open Windows sandbox
3. From https://github.com/Gnucash/gnucash/releases/tag/5.3 copy
   gnucash-5.3.setup.exe into the sandbox
4. Run this exe installer
5. From Windows menu, run 'install online price retrieval for gnucash'
6. Wait several minutes

### Result

Online quotes install fails. Reports testing error, warns "changes to succeed are limited", and prompts yes/no for user to "Use unaligned loads and stores?".

Brief error output here. Full output atttached.

```
Writing Makefile for Devel::CheckLib
Writing MYMETA.yml and MYMETA.json
  MATTN/Devel-CheckLib-1.16.tar.gz
  C:\Strawberry\perl\bin\perl.exe Makefile.PL -- OK
Running make for M/MA/MATTN/Devel-CheckLib-1.16.tar.gz
cp lib/Devel/CheckLib.pm blib\lib\Devel\CheckLib.pm
"C:\Strawberry\perl\bin\perl.exe" -MExtUtils::Command -e cp -- bin/use-devel-checklib blib\script\use-devel-checklib
pl2bat.bat blib\script\use-devel-checklib
  MATTN/Devel-CheckLib-1.16.tar.gz
  C:\STRAWB~1\c\bin\gmake.exe -- OK
Running make test for MATTN/Devel-CheckLib-1.16.tar.gz
"C:\Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/*.t
t/00-load.t ................... ok
t/analyze-binary.t ............ ok
t/bad-single-word-compiler.t .. ok
t/cmdline-LIBS-INC.t .......... ok
t/custom-function.t ........... ok
t/dash-l-libs.t ............... ok
t/exit_with_message.t ......... Use of uninitialized value $err in pattern match (m//) at t/exit_with_message.t line 17.

#   Failed test 'missing hlagh detected non-fatally'
t/exit_with_message.t ......... 1/1 #   at t/exit_with_message.t line 21.
#                   undef
#     doesn't match '/^Can't link\/include C library 'hlagh'/ms'
# Looks like you failed 1 test of 1.
t/exit_with_message.t ......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
t/flags.t ..................... ok
t/found.t ..................... ok
t/headers.t ................... ok
t/multi-word-compiler.t ....... ok
t/not_found.t ................. ok

Test Summary Report
-------------------
t/exit_with_message.t       (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=12, Tests=42, 10 wallclock secs ( 0.03 usr +  0.01 sys =  0.05 CPU)
Result: FAIL
Failed 1/12 test programs. 1/42 subtests failed.
gmake: *** [Makefile:890: test_dynamic] Error 255
  MATTN/Devel-CheckLib-1.16.tar.gz
  C:\STRAWB~1\c\bin\gmake.exe test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports MATTN/Devel-CheckLib-1.16.tar.gz
  YVES/Sereal-Encoder-5.004.tar.gz
  Has already been unwrapped into directory C:\STRAWB~1\cpan\build\Sereal-Encoder-5.004-0
Warning: Prerequisite 'Devel::CheckLib => 1.16' for 'YVES/Sereal-Encoder-5.004.tar.gz' failed when processing 'MATTN/Devel-CheckLib-1.16.tar.gz' with 'make_test => NO'. Continuing, but chances to succeed are limited.
Configuring Y/YV/YVES/Sereal-Encoder-5.004.tar.gz with Makefile.PL
USE_UNALIGNED not set in env. Use unaligned loads and stores? yes/no [no]
```

### Expected

Clean online quotes install as was in GnuCash 4.5

### Log

Attached [full-error-log.txt](https://github.com/finance-quote/finance-quote/files/12194659/full-error-log.txt)

**Comment by bpschuck** [comment] 2023-07-28 15:11
The problem is likely within the Windows Sandbox. Note the errors while installing dependencies, such as Devel::CheckLib. Not a Finance::Quote issue, but a user environment issue.

**Comment by diablodale** [comment] 2023-07-28 15:27
So that means it is a GnuCash setup issue.  Is there a way to help gnucash team know what your deependencies are? They would need to install them.

**Comment by bpschuck** [comment] 2023-07-28 15:38
CPAN automatically picks up dependencies. I think the issue may have something to do with running in the sandbox environment. I know you may not want to, but please try to install GnuCash and Perl/Finance::Quote not in the Windows Sandbox.

**Comment by diablodale** [comment] 2023-07-28 16:08
Does not appear to be sandbox. Finance successfully installed when I followed cpan instructions

1. open windows sandbox as in OP
2. install strawberry 5.32.1.1 32 bit from https://strawberryperl.com/
3. open strawberry prompt
4. follow cpan instructions from https://www.cpan.org/modules/INSTALL.html by first `cpan App::cpanminus`
5. and then `cpanm Finance::Quote`

### Result

step 4 succeeded with no errors
step 5 succeeded with no errors

```
--> Working on Finance::Quote
Fetching http://www.cpan.org/authors/id/B/BP/BPSCHUCK/Finance-Quote-1.57.tar.gz ... OK
Configuring Finance-Quote-1.57 ... OK
==> Found dependencies: Spreadsheet::XLSX, Web::Scraper, HTML::TokeParser::Simple, DateTime::Format::Strptime, Date::Manip, Readonly, HTML::TreeBuilder::XPath, String::Util, Test::Perl::Critic, DateTime::Format::ISO8601, Date::Range, Date::Simple, HTML::TableExtract
--> Working on Spreadsheet::XLSX
...
Building and testing Finance-Quote-1.57 ... OK
Successfully installed Finance-Quote-1.57
34 distributions installed
```

**Comment by bpschuck** [comment] 2023-07-28 16:16
Glad you figured it out. Then it is something about being installed via the GnuCash supplied tool. I am closing this issue.
Thanks.

**Closed by bpschuck** 2023-07-28 16:16 UTC

**Comment by diablodale** [comment] 2023-07-28 16:23
Agreed. This is a gnucash bug. 🫤
