### ISSUE TITLE
YahooJSON.pm is giving invalid cookie/crumb again

### ISSUE THREAD

**Issue by danmcnaul** [finance-quote/finance-quote#378] opened 2024-04-16 22:16 UTC
I'm running F::Q via GnuCash v5.4 and F::Q v1.58 on Win10.  I don't know how to check to see if someone has already reported this.

On April 10, 2024 the YahooJSON began returning the "invalid cookie / invalid crumb" error again. GnuCash returns a 401 (Unauthorized) error.  However, when I go directly to 

https://query2.finance.yahoo.com/v11/finance/quoteSummary/?symbol=T&modules=price,summaryDetail,defaultKeyStat

I get:

<html><body>
<div id="content"><div class="tabs tabs-tall "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item json is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"></div></div></div></div><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="Filter JSON" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">
  |  
-- | --
finance |  
result | null
error |  
code | "Unauthorized"
description | "Invalid Crumb"

</div></div></div></div>
</body>
</html>

We've experienced similar issues in the past with the YahooJSON where the URL or access was changed on us by Yahoo.

**Comment by bpschuck** [comment] 2024-04-16 23:00
One could look through the `Changes` file in this repo, or scan through open and closed issues and pull requests.

In any case, Yahoo made some changes about 2 weeks ago that caused the `yahoo_json` method to break. Fixed in release v1.60 uploaded to CPAN yesterday (2024-04-15) evening.

**Comment by danmcnaul** [comment] 2024-04-17 00:10
Thank you.  I'm used to using Bugzilla. Bugzilla is probably no longer used.

Thanks for the quick turn around on syncing up with Yahoo Finance changes. F::Q has become an important tool for me.

**Comment by bpschuck** [comment] 2024-04-17 00:22
GnuCash still uses BugZilla. Finance::Quote used to use the CPAN Request Tracker ( https://rt.cpan.org/Dist/Display.html?Status=__Active__&Queue=Finance-Quote), but I rarely check that.

Just curious, do you use Finance::Quote because you use from GnuCash? Or some other OpenSource finance project or your own scripts and apps?

Lastly, I'm going to close this issue.

Bruce S

**Closed by bpschuck** 2024-04-17 00:22 UTC

**Comment by carlosala** [comment] 2024-04-17 06:50
It seems like is a duplicate of #373

**Comment by bpschuck** [comment] 2024-04-17 15:06
> It seems like is a duplicate of #373

No it's not... if you pay attention @danmcnaul was using v1.58...
