### ISSUE TITLE
Finance::Quote: 1.5301 fail to retrieve stock data with yahoo_json method

### ISSUE THREAD

**Issue by Adriano-Baldi** [finance-quote/finance-quote#264] opened 2023-04-19 23:35 UTC
With GnuCash Version: 4.14
Build ID: Flathub 4.14
Finance::Quote: 1.5301

Today 04/19/23 I can't download any quotes with yahoo_json, while I have no problems with Alphavantage.

[📦 org.gnucash.GnuCash ~]$ gnc-fq-dump yahoo_json USDEUR=X
Finance::Quote fields Gnucash uses:
    symbol: USDEUR=X             <=== required
      date: ** missing **        <=== recommended
  currency: ** missing **        <=== required
      last: **missing**          <=\
       nav: **missing**          <=== one of these
     price: **missing**          <=/
  timezone:                      <=== optional

** This stock quote cannot be used by GnuCash!

Until yesterday I had no problems, as you can see from a previous recording

[📦 org.gnucash.GnuCash ~]$ gnc-fq-dump yahoo_json USDEUR=X
Finance::Quote fields Gnucash uses:
    symbol: USDEUR=X             <=== required
      date: 08/31/2022           <=== recommended
  currency: EUR                  <=== required
      last: 0.9966               <=\
       nav:                      <=== one of these
     price:                      <=/
  timezone:                      <=== optional

Is anyone else having the same problems?

**Comment by bpschuck** [comment] 2023-04-20 00:06
Unfortunately Yahoo appears to no longer allow unrestricted access to JSON data quotes via the https://query1.finance.yahoo.com/v7/finance/quote?symbols= URL.
Workaround would be to utilize other modules where possible.

**Comment by bpschuck** [comment] 2023-04-20 01:39
It's not JSON, but a query such as `curl --silent 'https://query1.finance.yahoo.com/v7/finance/download/USDEUR=X'` returns:
```
Date,Open,High,Low,Close,Adj Close,Volume
2023-04-20,0.912600,0.913200,0.912100,0.912200,0.912200,0 
```

Since it's not JSON will probably just create a new module Finance::Quote::Yahoo or Finance::Quote::YahooCSV to replace YahooJSON. Not sure when I'll be able to work on it, hopefully another contributor will step up to the plate.

**Comment by bzbarsky** [comment] 2023-04-20 05:09
It looks like `https://query1.finance.yahoo.com/v10/finance/quoteSummary/USDEUR=X?modules=price` (or `https://query1.finance.yahoo.com/v10/finance/quoteSummary/VEMAX?modules=price` or equivalent for other symbols) returns the needed data as JSON.  Some of the JSON is a bit different from the old `v7/finance/quote` endpoint (e.g. some of the prices seem to be objects with `raw` (number) and `fmt` (string) properties), but in general it's pretty close.

It's probably also possible to do something like `https://query1.finance.yahoo.com/v7/finance/chart/USDEUR=X?symbol=USDEUR=X&interval=1m&period1=1681967151&period2=1681967151` where `period1` and `period2` are the current unix time (setting them equal should just get you as single data point, not a whole time series).   But that seems more complicated than the v10 endpoint above.

**Comment by gibelium** [comment] 2023-04-20 15:05
V6 endpoint seems to work pretty well:

https://query1.finance.yahoo.com/v6/finance/quote?symbols=USDEUR=X
https://query1.finance.yahoo.com/v6/finance/quote?symbols=APPL
https://query1.finance.yahoo.com/v6/finance/quote?symbols=BTC-USD

**Comment by whoosit** [comment] 2023-04-20 17:20
I just now retried "Get Quotes" and it is working again after having not worked since yesterday evening.  Someone at Yahoo backed out their change??

**Comment by avlsi** [comment] 2023-04-20 17:39
Confirmed working for v7.

**Comment by Adriano-Baldi** [comment] 2023-04-20 19:13
I agree too. Now everything is working normally.
Let's hope it continues to work.
However, I have been using this software for 18 years now, and whenever something like this happens we have always found a solution quickly. 
The strength of the open source community is unrivaled !
Thank's to @avlsi for sharing this alternative.
I agree with @bpschuck  if the problem does not recur we can close the tread as solved.
Thank's to all.

**Comment by bpschuck** [comment] 2023-04-30 23:49
Yahoo has restored the original functionality.

**Comment by Tottitov** [comment] 2023-05-05 01:58
anyone having issues again?

**Comment by bpschuck** [comment] 2023-05-05 02:14
Notice, I reopened the issue and posted a message to the gnucash-user email list.
Will wait a day or so, then look to changing the module to use one of the sources noted in the comments here.

**Comment by lodenrogue** [comment] 2023-05-05 05:01
Happening again for me as well

**Comment by avlsi** [comment] 2023-05-05 11:55
I also confirm that the problem has resurfaced. Time to move to a reliable version of yahoo_json.

**Comment by jsjuni** [comment] 2023-05-07 14:11
It's working again.

**Comment by dima-ser** [comment] 2023-05-07 14:23
Still broke for me. How do I implement the workaround posted in this thread, I use finance quote with GnuCash on Windows. Or is there another free provider besides Yahoo we can use?

**Comment by Adriano-Baldi** [comment] 2023-05-08 07:28
> Still broke for me. How do I implement the workaround posted in this thread, I use finance quote with GnuCash on Windows. Or is there another free provider besides Yahoo we can use?

I changed the following line in the YahooJSON.pm file from "v7" to "v6" and this works for me. 

#my $YIND_URL_HEAD = 'https://query1.finance.yahoo.com/v7/finance/quote?symbols=';
my $YIND_URL_HEAD = 'https://query1.finance.yahoo.com/v6/finance/quote?symbols=';

**Comment by lodenrogue** [comment] 2023-05-09 19:55
Do we know when this fix will be released?

**Comment by ajgringo619** [comment] 2023-05-10 01:46
> > Still broke for me. How do I implement the workaround posted in this thread, I use finance quote with GnuCash on Windows. Or is there another free provider besides Yahoo we can use?
> 
> I changed the following line in the YahooJSON.pm file from "v7" to "v6" and this works for me.
> 
> #my $YIND_URL_HEAD = 'https://query1.finance.yahoo.com/v7/finance/quote?symbols='; my $YIND_URL_HEAD = 'https://query1.finance.yahoo.com/v6/finance/quote?symbols=';

I tried this and it caused my GnuCash (Linux) to coredump. What version of GnuCash are you running?

**Comment by bpschuck** [comment] 2023-05-10 01:56
Closing. F::Q v1.55 will have working URL.

**Closed by bpschuck** 2023-05-10 01:56 UTC
